use_frameworks!

platform :ios, '8.0'

target 'CDHorizontalScrollView_Example' do
  pod 'CDHorizontalScrollView', :path => '../'

  target 'CDHorizontalScrollView_Tests' do
    inherit! :search_paths

    
  end
end
